version: '3'
services:
  stuffs-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "8000:80"
    volumes:
      - .:/code
    depends_on:
      stuffs-mysql:
        condition: service_healthy
    command: bash -c "python3 /code/models/create_db.py"
    networks:
      - stuffs-backend
  stuffs-mysql:
    image: mysql:9
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - "8001:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 2
    networks:
      - stuffs-backend

networks:
  stuffs-backend:
    driver: bridge